<a href="https://colab.research.google.com/github/nestorm94/Aprendizaje_Maquinas/blob/main/NestorM_Quiz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.metrics import pairwise_distances
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_validate

In [ ]:
datos = np.array([[3, np.nan, 4],
                 [18, 15, 12],
                 [19, np.nan, 18],
                 [2, 18, 4],
                 [3, 2, 8],
                 [4, 10, 5],
                 [4, 0, 10],
                 [10, 20, 10],
                 ])

In [ ]:
datos

array([[ 3., nan,  4.],
       [18., 15., 12.],
       [19., nan, 18.],
       [ 2., 18.,  4.],
       [ 3.,  2.,  8.],
       [ 4., 10.,  5.],
       [ 4.,  0., 10.],
       [10., 20., 10.]])

In [ ]:
colA = datos[:, 0]
colB = datos[:, -1]
colC = datos[:, 1]
datos_n = np.c_[colA, colB, colC]

In [ ]:
datos_n

array([[ 3.,  4., nan],
       [18., 12., 15.],
       [19., 18., nan],
       [ 2.,  4., 18.],
       [ 3.,  8.,  2.],
       [ 4.,  5., 10.],
       [ 4., 10.,  0.],
       [10., 10., 20.]])

In [ ]:
dist = pairwise_distances(datos_n[:, :2])

In [ ]:
dist

array([[ 0.        , 17.        , 21.26029163,  1.        ,  4.        ,
         1.41421356,  6.08276253,  9.21954446],
       [17.        ,  0.        ,  6.08276253, 17.88854382, 15.5241747 ,
        15.65247584, 14.14213562,  8.24621125],
       [21.26029163,  6.08276253,  0.        , 22.02271555, 18.86796226,
        19.84943324, 17.        , 12.04159458],
       [ 1.        , 17.88854382, 22.02271555,  0.        ,  4.12310563,
         2.23606798,  6.32455532, 10.        ],
       [ 4.        , 15.5241747 , 18.86796226,  4.12310563,  0.        ,
         3.16227766,  2.23606798,  7.28010989],
       [ 1.41421356, 15.65247584, 19.84943324,  2.23606798,  3.16227766,
         0.        ,  5.        ,  7.81024968],
       [ 6.08276253, 14.14213562, 17.        ,  6.32455532,  2.23606798,
         5.        ,  0.        ,  6.        ],
       [ 9.21954446,  8.24621125, 12.04159458, 10.        ,  7.28010989,
         7.81024968,  6.        ,  0.        ]])

In [ ]:
uno = (datos_n[3][2] + datos_n[4][2] + datos_n[5][2]) / 3
dos = (datos_n[1][2] + datos_n[6][2] + datos_n[7][2]) / 3
print("número uno: ", uno, "número dos: ", dos)

número uno:  10.0 número dos:  11.666666666666666


In [ ]:
datos_n[0][2] = uno
datos_n[2][2] = dos

In [ ]:
datos_n

array([[ 3.        ,  4.        , 10.        ],
       [18.        , 12.        , 15.        ],
       [19.        , 18.        , 11.66666667],
       [ 2.        ,  4.        , 18.        ],
       [ 3.        ,  8.        ,  2.        ],
       [ 4.        ,  5.        , 10.        ],
       [ 4.        , 10.        ,  0.        ],
       [10.        , 10.        , 20.        ]])

In [ ]:
knnImputer = KNNImputer(n_neighbors=3)
knnImputer.fit(datos_n)
knnImputer.transform(datos_n)

array([[ 3.        ,  4.        , 10.        ],
       [18.        , 12.        , 15.        ],
       [19.        , 18.        , 11.66666667],
       [ 2.        ,  4.        , 18.        ],
       [ 3.        ,  8.        ,  2.        ],
       [ 4.        ,  5.        , 10.        ],
       [ 4.        , 10.        ,  0.        ],
       [10.        , 10.        , 20.        ]])