In [65]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import plot_tree
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from sklearn.metrics import mean_squared_error, r2_score
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [47]:
np.random.seed(123)
notas = np.random.uniform(0,5,(30,4))

students = pd.DataFrame(data=notas,
                          columns = ["NotaProg","NotaCalculo","NotaEtica","NotaML"])

In [ ]:
students

In [49]:
students["ApruebaMl"] = students["NotaML"] >= 3.0

In [50]:
train, test = train_test_split(students, test_size=0.3,random_state=123)

In [51]:
x_train = train[["NotaProg","NotaCalculo","NotaEtica"]]
y_train= train["ApruebaMl"]

In [52]:
x_test = test[["NotaProg","NotaCalculo","NotaEtica"]]
y_test= test["ApruebaMl"]

In [53]:
modelo = DecisionTreeClassifier()

In [54]:
modelo.fit(x_train, y_train)

DecisionTreeClassifier()

In [55]:
modelo.predict(x_train)

array([ True, False, False,  True, False, False, False, False, False,
        True, False, False,  True,  True, False,  True,  True, False,
       False,  True, False])

In [56]:
modelo.predict(x_test)

array([False,  True, False, False,  True, False,  True, False, False])

In [57]:
accuracy_score(y_train,modelo.predict(x_train))*100

100.0

In [58]:
accuracy_score(y_test,modelo.predict(x_test))*100

66.66666666666666

In [63]:
modelo.predict([[0,0,0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([ True])

In [73]:
x_train = train[["NotaProg","NotaCalculo","NotaEtica"]]
y_train= train["NotaML"]

In [74]:
x_test = test[["NotaProg","NotaCalculo","NotaEtica"]]
y_test= test["NotaML"]

In [75]:
modelo = DecisionTreeRegressor()
modelo.fit(x_train, y_train)

DecisionTreeRegressor()

In [76]:
modelo.predict(x_test)

array([4.42663413, 2.9721594 , 2.50918338, 1.94475287, 3.37344525,
       1.21833187, 0.65447475, 1.21833187, 1.21833187])

In [77]:
modelo.predict([[5.0,5.0,5.0]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(


array([1.21833187])