<a href="https://colab.research.google.com/github/nestorm94/Aprendizaje_Maquinas/blob/main/Quiz_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [26]:
from sklearn.metrics import pairwise_distances
from sklearn.neighbors import KNeighborsClassifier,KNeighborsRegressor
import pandas as pd
import numpy as np
import math

x1    [2,,1,5 ,7,9,1,0,-2,-1]

x2    [1,-3,0,2,1,2,1,-1,-3,5]

x3    [1,1,2,2,2,10,1,-11,2,-4]

x4    [2,0,0,1,3,7,2,-3,-2,-1]

y     [1,0,0,1,2,0,1,1,2,2]

In [11]:
df= pd.DataFrame({"x1": [2,3,1,5 ,7,9,1,0,-2,-1],
                  "x2": [1,-3,0,2,1,2,1,-1,-3,5],
                  "x3": [1,1,2,2,2,10,1,-11,2,-4],
                  "x4": [2,0,0,1,3,7,2,-3,-2,-1],
                  "y":  [1,0,0,1,2,0,1,1,2,2]})

In [12]:

X_test = np.array([[1, 3, 2, -3]])

k = 3
df['distance'] = np.sqrt(np.sum((df[['x1', 'x2', 'x3', 'x4']] - X_test) ** 2, axis=1))
nearest_neighbors = df.nsmallest(k, 'distance')
nearest_labels = nearest_neighbors['y'].values
unique_labels, counts = np.unique(nearest_labels, return_counts=True)
probabilities = counts / k
predict_proba_result = {label: probability for label, probability in zip(unique_labels, probabilities)}
print("Resultado de predict_proba:", predict_proba_result)

Resultado de predict_proba: {0: 0.3333333333333333, 1: 0.6666666666666666}


In [17]:
nearest_labels

array([0, 1, 1])

In [13]:
x=df[["x1", "x2","x3", "x4"]]
y=df["y"]

In [14]:
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x,y)
print(model.predict([[1, 3, 2, -3]]))
print(model.predict_proba([[1, 3, 2, -3]]))

[1]
[[0.33333333 0.66666667 0.        ]]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [15]:
pairwise_distances(x,[[1, 3, 2, -3]])

array([[ 5.56776436],
       [ 7.07106781],
       [ 4.24264069],
       [ 5.74456265],
       [ 8.71779789],
       [15.13274595],
       [ 5.47722558],
       [13.6381817 ],
       [ 6.78232998],
       [ 6.92820323]])

In [16]:
df['distance']

0     5.567764
1     7.071068
2     4.242641
3     5.744563
4     8.717798
5    15.132746
6     5.477226
7    13.638182
8     6.782330
9     6.928203
Name: distance, dtype: float64

#. parte 2


In [35]:
df_2 = pd.DataFrame({"X1": [3, 2, 3, 1, 4, 5],
                  "X2":[1, 5, 1, 3, 1, 2],
                  "X3": [4, 1, 4, 2, 1, 4],
                  "y":[4.1, 4.3, 2.1, 3.3, 4.1, 3.5]})

In [36]:
x_1= df_2[["X1", "X2","X3"]]
y_1=df_2["y"]

In [37]:
pairwise_distances(x_1,[[0, 1, 3]])

array([[3.16227766],
       [4.89897949],
       [3.16227766],
       [2.44948974],
       [4.47213595],
       [5.19615242]])

In [39]:
mode_l = KNeighborsRegressor(n_neighbors=3)
mode_l.fit(x_1,y_1)
#print(mode_l.predict([[0, 1, 3]]))
print(mode_l.predict([[0, 1, 3]]))

[3.16666667]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(
